version: "3.9"

services:
  database:
    image: "mongo"
    ports:
      - 27000:27017
    volumes:
      - dbdata:/data/db
    command: mongoimport --host database -d mns -c customer --type json --file ./setup/data/customer.json

  web:
    build: .
    depends_on: ["database"]
    restart: always
    ports:
      - 3000:3000
    # volumes:
    #   - ./:/usr/app/src
    #   - node_modules:/usr/app/src/node_modules

volumes:
  dbdata:
  node_modules:
